### ISSUE TITLE
How to cite this project?

### ISSUE THREAD

**Issue by jschoete** [acasteigts/temporal-graph-generator#1]
I'd like to cite this project. GitHub seems to have an easy proposition for this using citation files:

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

In the meantime, is it ok if I cite this as follows?

@inproceedings{casteigts2020stgen,
  title={STGen (A Generator for Simple Temporal Graphs)},
  author={Casteigts, Arnaud},
  booktitle={3rd workshop on Algorithmic Aspects of Temporal Graphs (ICALP)},
  year={2020},
  url={https://github.com/acasteigts/STGen}
}

**Comment by acasteigts** [comment]
Hi Jason,

Your suggestion looks good to me. Just one detail, instead of ICALP, you may write AATG@ICALP. I think the '@' needs to be protected, so I have also added a second pair of brakets:

@inproceedings{casteigts2020stgen,
title={STGen (A Generator for Simple Temporal Graphs)},
author={Casteigts, Arnaud},
booktitle={{3rd workshop on Algorithmic Aspects of Temporal Graphs (AATG@ICALP)}},
year={2020},
url={https://github.com/acasteigts/STGen}
}

Can you please test and let me know?

**Comment by jschoete** [comment]
The brackets work fine concerning the `@`. In my case, I had to change the author to `Arnaud Casteigts` or it would show as `____`. I also added brackets around STGen so as not to obtain `stgen`:

@inproceedings{casteigts2020stgen,
  title={{STGen (A Generator for Simple Temporal Graphs)}},
  author={Arnaud Casteigts},
  booktitle={{3rd workshop on Algorithmic Aspects of Temporal Graphs (AATG@ICALP)}},
  year={2020},
  url={https://github.com/acasteigts/STGen}
}

Thanks!

**Comment by acasteigts** [comment]
Thanks Jason!
